export let delivery_pending_list = [
    {
        restockID   : "Re-O-000135",
        item        : "Black Pepper",
        supplier    : "Godagama Distributors",
        issueddate  : "2021-10-28",
        status      : "Pending",
        timeremain  : "07:00",
        quantity    : "3 kg",
        price       : "5,400",
    },
    {
        restockID   : "Re-F-000134",
        item        : "Pineapple",
        supplier    : "Healthy Farmers",
        issueddate  : "2021-10-29",
        status      : "Pending",
        timeremain  : "08:00",
        quantity    : "50 Units",
        price       : "10,000",
    },
    {
        restockID  : "Re-V-000133",
        item        : "Potato",
        supplier    : "R.R.Distributors",
        issueddate  : "2021-10-31",
        status      : "Pending",
        timeremain  : "23:00",
        quantity    : "50 kg",
        price       : "11,000",
    },
    {
        restockID   : "Re-M-000132",
        item        : "Egg",
        supplier    : "R.L.Farm House",
        issueddate  : "2021-11-01",
        status      : "Pending",
        timeremain  : "24:00",
        quantity    : "500 Units",
        price       : "10,500",
    },
    {
        restockID   : "Re-V-000131",
        item        : "Tomato",
        supplier    : "H.T.Farmers",
        issueddate  : "2021-10-26",
        status      : "Completed",
        timeremain  : "----",
        quantity    : "20 kg",
        price       : "10,000",
    },
]